// ==============================================================================
// NIRVANA - GameItem Model
// Description: Offline bundled visual items with high-quality real image assets
// for Remember Objects and Grocery Memory games.
// ==============================================================================

import 'package:flutter/material.dart';

class GameItem {
  final String id;
  final String name;
  final String imagePath;
  final String emoji;
  final IconData fallbackIcon;
  final Color tintColor;
  final String category;

  const GameItem({
    required this.id,
    required this.name,
    required this.imagePath,
    this.emoji = '📦',
    this.fallbackIcon = Icons.category_rounded,
    this.tintColor = const Color(0xFF0F766E),
    required this.category,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameItem && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  /// Full 30 Object Items catalogue for Remember Objects Game
  static const List<GameItem> defaultEverydayItems = [
    GameItem(
      id: 'rose',
      name: 'Garden Rose',
      imagePath: 'assets/images/objects/rose.png',
      emoji: '🌹',
      fallbackIcon: Icons.local_florist_rounded,
      tintColor: Color(0xFFE91E63),
      category: 'garden',
    ),
    GameItem(
      id: 'glasses',
      name: 'Reading Glasses',
      imagePath: 'assets/images/objects/glasses.png',
      emoji: '👓',
      fallbackIcon: Icons.visibility_rounded,
      tintColor: Color(0xFF455A64),
      category: 'personal',
    ),
    GameItem(
      id: 'camera',
      name: 'Photo Camera',
      imagePath: 'assets/images/objects/camera.png',
      emoji: '📷',
      fallbackIcon: Icons.camera_alt_rounded,
      tintColor: Color(0xFF5E35B1),
      category: 'leisure',
    ),
    GameItem(
      id: 'umbrella',
      name: 'Umbrella',
      imagePath: 'assets/images/objects/umbrella.png',
      emoji: '☂️',
      fallbackIcon: Icons.umbrella_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'clothing',
    ),
    GameItem(
      id: 'key',
      name: 'Key',
      imagePath: 'assets/images/objects/key.png',
      emoji: '🔑',
      fallbackIcon: Icons.vpn_key_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'household',
    ),
    GameItem(
      id: 'tea_cup',
      name: 'Tea Cup',
      imagePath: 'assets/images/objects/tea_cup.png',
      emoji: '☕',
      fallbackIcon: Icons.local_cafe_rounded,
      tintColor: Color(0xFF795548),
      category: 'kitchen',
    ),
    GameItem(
      id: 'clock',
      name: 'Clock',
      imagePath: 'assets/images/objects/clock.png',
      emoji: '⏰',
      fallbackIcon: Icons.access_time_filled_rounded,
      tintColor: Color(0xFF00897B),
      category: 'household',
    ),
    GameItem(
      id: 'book',
      name: 'Book',
      imagePath: 'assets/images/objects/book.png',
      emoji: '📖',
      fallbackIcon: Icons.menu_book_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'leisure',
    ),
    GameItem(
      id: 'apple',
      name: 'Apple',
      imagePath: 'assets/images/objects/apple.png',
      emoji: '🍎',
      fallbackIcon: Icons.apple,
      tintColor: Color(0xFFD32F2F),
      category: 'fruit',
    ),
    GameItem(
      id: 'banana',
      name: 'Banana',
      imagePath: 'assets/images/objects/banana.png',
      emoji: '🍌',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'fruit',
    ),
    GameItem(
      id: 'water_bottle',
      name: 'Water Bottle',
      imagePath: 'assets/images/objects/water_bottle.png',
      emoji: '🧴',
      fallbackIcon: Icons.water_drop_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'kitchen',
    ),
    GameItem(
      id: 'handbag',
      name: 'Handbag',
      imagePath: 'assets/images/objects/handbag.png',
      emoji: '👜',
      fallbackIcon: Icons.shopping_bag_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'personal',
    ),
    GameItem(
      id: 'cap',
      name: 'Cap',
      imagePath: 'assets/images/objects/cap.png',
      emoji: '🧢',
      fallbackIcon: Icons.sports_baseball_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'clothing',
    ),
    GameItem(
      id: 'pencil',
      name: 'Pencil',
      imagePath: 'assets/images/objects/pencil.png',
      emoji: '✏️',
      fallbackIcon: Icons.edit_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'leisure',
    ),
    GameItem(
      id: 'radio',
      name: 'Radio',
      imagePath: 'assets/images/objects/radio.png',
      emoji: '📻',
      fallbackIcon: Icons.radio_rounded,
      tintColor: Color(0xFF5D4037),
      category: 'leisure',
    ),
    GameItem(
      id: 'toothbrush',
      name: 'Toothbrush',
      imagePath: 'assets/images/objects/toothbrush.png',
      emoji: '🪥',
      fallbackIcon: Icons.cleaning_services_rounded,
      tintColor: Color(0xFF03A9F4),
      category: 'personal',
    ),
    GameItem(
      id: 'candle',
      name: 'Candle',
      imagePath: 'assets/images/objects/candle.png',
      emoji: '🕯️',
      fallbackIcon: Icons.light_mode_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'household',
    ),
    GameItem(
      id: 'plant',
      name: 'Plant',
      imagePath: 'assets/images/objects/plant.png',
      emoji: '🪴',
      fallbackIcon: Icons.yard_rounded,
      tintColor: Color(0xFF388E3C),
      category: 'garden',
    ),
    GameItem(
      id: 'spoon',
      name: 'Spoon',
      imagePath: 'assets/images/objects/spoon.png',
      emoji: '🥄',
      fallbackIcon: Icons.restaurant_rounded,
      tintColor: Color(0xFF78909C),
      category: 'kitchen',
    ),
    GameItem(
      id: 'rice_bowl',
      name: 'Rice Bowl',
      imagePath: 'assets/images/objects/rice_bowl.png',
      emoji: '🍚',
      fallbackIcon: Icons.ramen_dining_rounded,
      tintColor: Color(0xFF37474F),
      category: 'kitchen',
    ),
    GameItem(
      id: 'basket',
      name: 'Basket',
      imagePath: 'assets/images/objects/basket.png',
      emoji: '🧺',
      fallbackIcon: Icons.shopping_basket_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'household',
    ),
    GameItem(
      id: 'shoe',
      name: 'Shoe',
      imagePath: 'assets/images/objects/shoe.png',
      emoji: '👞',
      fallbackIcon: Icons.roller_skating_rounded,
      tintColor: Color(0xFF4E342E),
      category: 'clothing',
    ),
    GameItem(
      id: 'scarf',
      name: 'Scarf',
      imagePath: 'assets/images/objects/scarf.png',
      emoji: '🧣',
      fallbackIcon: Icons.dry_cleaning_rounded,
      tintColor: Color(0xFFC62828),
      category: 'clothing',
    ),
    GameItem(
      id: 'wallet',
      name: 'Wallet',
      imagePath: 'assets/images/objects/wallet.png',
      emoji: '👛',
      fallbackIcon: Icons.account_balance_wallet_rounded,
      tintColor: Color(0xFF5D4037),
      category: 'personal',
    ),
    GameItem(
      id: 'comb',
      name: 'Comb',
      imagePath: 'assets/images/objects/comb.png',
      emoji: '🪮',
      fallbackIcon: Icons.content_cut_rounded,
      tintColor: Color(0xFF795548),
      category: 'personal',
    ),
    GameItem(
      id: 'mug',
      name: 'Mug',
      imagePath: 'assets/images/objects/mug.png',
      emoji: '☕',
      fallbackIcon: Icons.coffee_rounded,
      tintColor: Color(0xFF00897B),
      category: 'kitchen',
    ),
    GameItem(
      id: 'lamp',
      name: 'Lamp',
      imagePath: 'assets/images/objects/lamp.png',
      emoji: '🛋️',
      fallbackIcon: Icons.lightbulb_outline_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'household',
    ),
    GameItem(
      id: 'bell',
      name: 'Bell',
      imagePath: 'assets/images/objects/bell.png',
      emoji: '🔔',
      fallbackIcon: Icons.notifications_active_rounded,
      tintColor: Color(0xFFFFB300),
      category: 'household',
    ),
    GameItem(
      id: 'watch',
      name: 'Watch',
      imagePath: 'assets/images/objects/watch.png',
      emoji: '⌚',
      fallbackIcon: Icons.watch_rounded,
      tintColor: Color(0xFF3E2723),
      category: 'personal',
    ),
    GameItem(
      id: 'sweater',
      name: 'Sweater',
      imagePath: 'assets/images/objects/sweater.png',
      emoji: '🧥',
      fallbackIcon: Icons.checkroom_rounded,
      tintColor: Color(0xFF546E7A),
      category: 'clothing',
    ),
  ];

  /// Full 30 Grocery Items catalogue for Grocery Memory Game
  static const List<GameItem> defaultGroceryItems = [
    GameItem(
      id: 'groc_rice',
      name: 'Rice',
      imagePath: 'assets/images/groceries/rice.png',
      emoji: '🍚',
      fallbackIcon: Icons.rice_bowl_rounded,
      tintColor: Color(0xFF37474F),
      category: 'grains',
    ),
    GameItem(
      id: 'groc_dal',
      name: 'Dal',
      imagePath: 'assets/images/groceries/dal.png',
      emoji: '🍲',
      fallbackIcon: Icons.soup_kitchen_rounded,
      tintColor: Color(0xFFF57F17),
      category: 'pulses',
    ),
    GameItem(
      id: 'groc_wheat',
      name: 'Wheat',
      imagePath: 'assets/images/groceries/wheat.png',
      emoji: '🌾',
      fallbackIcon: Icons.grass_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'grains',
    ),
    GameItem(
      id: 'groc_salt',
      name: 'Salt',
      imagePath: 'assets/images/groceries/salt.png',
      emoji: '🧂',
      fallbackIcon: Icons.grain_rounded,
      tintColor: Color(0xFF78909C),
      category: 'spices',
    ),
    GameItem(
      id: 'groc_sugar',
      name: 'Sugar',
      imagePath: 'assets/images/groceries/sugar.png',
      emoji: '🍬',
      fallbackIcon: Icons.kitchen_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'pantry',
    ),
    GameItem(
      id: 'groc_oil',
      name: 'Cooking Oil',
      imagePath: 'assets/images/groceries/cooking_oil.png',
      emoji: '🛢️',
      fallbackIcon: Icons.opacity_rounded,
      tintColor: Color(0xFFFFB300),
      category: 'pantry',
    ),
    GameItem(
      id: 'groc_banana',
      name: 'Banana',
      imagePath: 'assets/images/groceries/banana.png',
      emoji: '🍌',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_apple',
      name: 'Apple',
      imagePath: 'assets/images/groceries/apple.png',
      emoji: '🍎',
      fallbackIcon: Icons.apple,
      tintColor: Color(0xFFD32F2F),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_mango',
      name: 'Mango',
      imagePath: 'assets/images/groceries/mango.png',
      emoji: '🥭',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_orange',
      name: 'Orange',
      imagePath: 'assets/images/groceries/orange.png',
      emoji: '🍊',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFFFB8C00),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_coconut',
      name: 'Coconut',
      imagePath: 'assets/images/groceries/coconut.png',
      emoji: '🥥',
      fallbackIcon: Icons.circle_outlined,
      tintColor: Color(0xFF5D4037),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_cabbage',
      name: 'Cabbage',
      imagePath: 'assets/images/groceries/cabbage.png',
      emoji: '🥬',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF43A047),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_peas',
      name: 'Peas',
      imagePath: 'assets/images/groceries/peas.png',
      emoji: '🟢',
      fallbackIcon: Icons.lens_rounded,
      tintColor: Color(0xFF7CB342),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_garlic',
      name: 'Garlic',
      imagePath: 'assets/images/groceries/garlic.png',
      emoji: '🧄',
      fallbackIcon: Icons.spa_rounded,
      tintColor: Color(0xFF90A4AE),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_sugarcane',
      name: 'Sugarcane',
      imagePath: 'assets/images/groceries/sugarcane.png',
      emoji: '🎋',
      fallbackIcon: Icons.park_rounded,
      tintColor: Color(0xFF689F38),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_milk',
      name: 'Milk',
      imagePath: 'assets/images/groceries/milk.png',
      emoji: '🥛',
      fallbackIcon: Icons.local_drink_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'dairy',
    ),
    GameItem(
      id: 'groc_bread',
      name: 'Bread',
      imagePath: 'assets/images/groceries/bread.png',
      emoji: '🍞',
      fallbackIcon: Icons.bakery_dining_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'bakery',
    ),
    GameItem(
      id: 'groc_tea',
      name: 'Tea',
      imagePath: 'assets/images/groceries/tea.png',
      emoji: '🍵',
      fallbackIcon: Icons.emoji_food_beverage_rounded,
      tintColor: Color(0xFF388E3C),
      category: 'beverages',
    ),
    GameItem(
      id: 'groc_coffee',
      name: 'Coffee',
      imagePath: 'assets/images/groceries/coffee.png',
      emoji: '☕',
      fallbackIcon: Icons.local_cafe_rounded,
      tintColor: Color(0xFF4E342E),
      category: 'beverages',
    ),
    GameItem(
      id: 'groc_biscuits',
      name: 'Biscuits',
      imagePath: 'assets/images/groceries/biscuits.png',
      emoji: '🍪',
      fallbackIcon: Icons.cookie_rounded,
      tintColor: Color(0xFFFB8C00),
      category: 'snacks',
    ),
    GameItem(
      id: 'groc_eggs',
      name: 'Eggs',
      imagePath: 'assets/images/groceries/eggs.png',
      emoji: '🥚',
      fallbackIcon: Icons.egg_rounded,
      tintColor: Color(0xFFFFB74D),
      category: 'dairy',
    ),
    GameItem(
      id: 'groc_potato',
      name: 'Potato',
      imagePath: 'assets/images/groceries/potato.png',
      emoji: '🥔',
      fallbackIcon: Icons.crop_square_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_tomato',
      name: 'Tomato',
      imagePath: 'assets/images/groceries/tomato.png',
      emoji: '🍅',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFFE53935),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_onion',
      name: 'Onion',
      imagePath: 'assets/images/groceries/onion.png',
      emoji: '🧅',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFF8E24AA),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_carrot',
      name: 'Carrot',
      imagePath: 'assets/images/groceries/carrot.png',
      emoji: '🥕',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_brinjal',
      name: 'Brinjal',
      imagePath: 'assets/images/groceries/brinjal.png',
      emoji: '🍆',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFF4A148C),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_green_chilli',
      name: 'Green Chilli',
      imagePath: 'assets/images/groceries/green_chilli.png',
      emoji: '🌶️',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF2E7D32),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_spinach',
      name: 'Spinach',
      imagePath: 'assets/images/groceries/spinach.png',
      emoji: '🥬',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF1B5E20),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_corn',
      name: 'Corn',
      imagePath: 'assets/images/groceries/corn.png',
      emoji: '🌽',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFDD835),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_honey',
      name: 'Honey',
      imagePath: 'assets/images/groceries/honey.png',
      emoji: '🍯',
      fallbackIcon: Icons.breakfast_dining_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'pantry',
    ),
  ];
}
