// ==============================================================================
// NIRVANA - GameItem Model
// Description: Offline bundled visual items with high-quality real image assets
// for Remember Objects and Grocery Memory games.
// ==============================================================================

import 'package:flutter/material.dart';

class GameItem {
  final String id;
  final String name;
  final String imagePath;
  final String emoji;
  final IconData fallbackIcon;
  final Color tintColor;
  final String category;

  const GameItem({
    required this.id,
    required this.name,
    required this.imagePath,
    this.emoji = '📦',
    this.fallbackIcon = Icons.category_rounded,
    this.tintColor = const Color(0xFF0F766E),
    required this.category,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameItem && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  /// Returns the localized name of the item for the given language code
  String localizedName(String languageCode) {
    final trans = _localizedNames[id];
    if (trans != null && trans.containsKey(languageCode)) {
      return trans[languageCode]!;
    }
    return name;
  }

  static const Map<String, Map<String, String>> _localizedNames = {
    // 30 Everyday Objects
    'rose': {
      'en': 'Garden Rose',
      'hi': 'गुलाब',
      'bn': 'গোলাপ ফুল',
      'as': 'গোলাপ ফুল',
      'ne': 'गुलाब',
    },
    'glasses': {
      'en': 'Reading Glasses',
      'hi': 'चश्मा',
      'bn': 'চশমা',
      'as': 'চশমা',
      'ne': 'चश्मा',
    },
    'camera': {
      'en': 'Photo Camera',
      'hi': 'कैमरा',
      'bn': 'ক্যামেরা',
      'as': 'কেমেৰা',
      'ne': 'क्यामेरा',
    },
    'umbrella': {
      'en': 'Umbrella',
      'hi': 'छाता',
      'bn': 'ছাতা',
      'as': 'ছাতি',
      'ne': 'छाता',
    },
    'key': {
      'en': 'Key',
      'hi': 'चाबी',
      'bn': 'চাবি',
      'as': 'চাবি',
      'ne': 'चाबी',
    },
    'tea_cup': {
      'en': 'Tea Cup',
      'hi': 'चाय का कप',
      'bn': 'চায়ের কাপ',
      'as': 'চাহৰ কাপ',
      'ne': 'चियाको कप',
    },
    'clock': {
      'en': 'Clock',
      'hi': 'घड़ी',
      'bn': 'ঘড়ি',
      'as': 'ঘড়ী',
      'ne': 'घडी',
    },
    'book': {
      'en': 'Book',
      'hi': 'किताब',
      'bn': 'বই',
      'as': 'কিতাপ',
      'ne': 'किताब',
    },
    'apple': {
      'en': 'Apple',
      'hi': 'सेब',
      'bn': 'আপেল',
      'as': 'আপেল',
      'ne': 'स्याउ',
    },
    'banana': {
      'en': 'Banana',
      'hi': 'केला',
      'bn': 'কলা',
      'as': 'কল',
      'ne': 'केरा',
    },
    'water_bottle': {
      'en': 'Water Bottle',
      'hi': 'पानी की बोतल',
      'bn': 'পানির বোতল',
      'as': 'পানীৰ বটল',
      'ne': 'पानीको बोतल',
    },
    'handbag': {
      'en': 'Handbag',
      'hi': 'पर्स / बैग',
      'bn': 'হ্যান্ডব্যাগ',
      'as': 'হেন্দবেগ',
      'ne': 'झोला',
    },
    'cap': {
      'en': 'Cap',
      'hi': 'टोपी',
      'bn': 'টুপি',
      'as': 'টুপি',
      'ne': 'टोपी',
    },
    'pencil': {
      'en': 'Pencil',
      'hi': 'पेंसिल',
      'bn': 'পেন্সিল',
      'as': 'পেঞ্চিল',
      'ne': 'पेन्सिल',
    },
    'radio': {
      'en': 'Radio',
      'hi': 'रेडियो',
      'bn': 'রেডিও',
      'as': 'ৰেডিঅ’',
      'ne': 'रेडियो',
    },
    'toothbrush': {
      'en': 'Toothbrush',
      'hi': 'टूथब्रश',
      'bn': 'টুথব্রাশ',
      'as': 'টুথব্ৰাছ',
      'ne': 'टुथब्रस',
    },
    'candle': {
      'en': 'Candle',
      'hi': 'मोमबत्ती',
      'bn': 'মোমবাতি',
      'as': 'মমবাতি',
      'ne': 'मैनबत्ती',
    },
    'plant': {
      'en': 'Plant',
      'hi': 'पौधा',
      'bn': 'গাছপুলি',
      'as': 'গছপুলি',
      'ne': 'बिरुवा',
    },
    'spoon': {
      'en': 'Spoon',
      'hi': 'चम्मच',
      'bn': 'চামচ',
      'as': 'চামুচ',
      'ne': 'चम्चा',
    },
    'rice_bowl': {
      'en': 'Rice Bowl',
      'hi': 'चावल का कटोरा',
      'bn': 'ভাতের বাটি',
      'as': 'ভাতৰ বাতি',
      'ne': 'भातको कचौरा',
    },
    'basket': {
      'en': 'Basket',
      'hi': 'टोकरी',
      'bn': 'ঝুড়ি',
      'as': 'ডলা / পাচি',
      'ne': 'टोकरी',
    },
    'shoe': {
      'en': 'Shoe',
      'hi': 'जूता',
      'bn': 'জুতো',
      'as': 'জোতা',
      'ne': 'जुत्ता',
    },
    'scarf': {
      'en': 'Scarf',
      'hi': 'दुपट्टा / स्कार्फ',
      'bn': 'স্কার্ফ',
      'as': 'স্কাৰ্ফ',
      'ne': 'गलबन्दी',
    },
    'wallet': {
      'en': 'Wallet',
      'hi': 'बटुआ',
      'bn': 'মানিব্যাগ',
      'as': 'পাৰ্চ',
      'ne': 'वालेट',
    },
    'comb': {
      'en': 'Comb',
      'hi': 'कंघी',
      'bn': 'চিরুনি',
      'as': 'ফণি',
      'ne': 'काँइयो',
    },
    'mug': {
      'en': 'Mug',
      'hi': 'मग',
      'bn': 'মগ',
      'as': 'মগ',
      'ne': 'मग',
    },
    'lamp': {
      'en': 'Lamp',
      'hi': 'दीपक / लैंप',
      'bn': 'প্রদীপ',
      'as': 'চাকি',
      'ne': 'बत्ती',
    },
    'bell': {
      'en': 'Bell',
      'hi': 'घंटी',
      'bn': 'ঘণ্টা',
      'as': 'ঘণ্টী',
      'ne': 'घण्टी',
    },
    'watch': {
      'en': 'Watch',
      'hi': 'हाथ घड़ी',
      'bn': 'হাতঘড়ি',
      'as': 'হাতঘড়ী',
      'ne': 'हातघडी',
    },
    'sweater': {
      'en': 'Sweater',
      'hi': 'स्वेटर',
      'bn': 'সোয়েটার',
      'as': 'ছুৱেটাৰ',
      'ne': 'स्वेटर',
    },

    // 30 Grocery Items
    'groc_rice': {
      'en': 'Rice',
      'hi': 'चावल',
      'bn': 'চাল',
      'as': 'চাউল',
      'ne': 'चामल',
    },
    'groc_dal': {
      'en': 'Dal',
      'hi': 'दाल',
      'bn': 'ডাল',
      'as': 'দাইল',
      'ne': 'दाल',
    },
    'groc_wheat': {
      'en': 'Wheat',
      'hi': 'गेहूं / आटा',
      'bn': 'গম / আটা',
      'as': 'গম / আটা',
      'ne': 'गहुँ',
    },
    'groc_salt': {
      'en': 'Salt',
      'hi': 'नमक',
      'bn': 'লবণ',
      'as': 'নিমখ',
      'ne': 'नुन',
    },
    'groc_sugar': {
      'en': 'Sugar',
      'hi': 'चीनी',
      'bn': 'চিনি',
      'as': 'চেনি',
      'ne': 'चिनी',
    },
    'groc_oil': {
      'en': 'Cooking Oil',
      'hi': 'तेल',
      'bn': 'রান্নার তেল',
      'as': 'খোৱা তেল',
      'ne': 'तेल',
    },
    'groc_banana': {
      'en': 'Banana',
      'hi': 'केला',
      'bn': 'কলা',
      'as': 'কল',
      'ne': 'কেरा',
    },
    'groc_apple': {
      'en': 'Apple',
      'hi': 'सेब',
      'bn': 'আপেল',
      'as': 'আপেল',
      'ne': 'स्याउ',
    },
    'groc_mango': {
      'en': 'Mango',
      'hi': 'आम',
      'bn': 'আম',
      'as': 'আম',
      'ne': 'आँप',
    },
    'groc_orange': {
      'en': 'Orange',
      'hi': 'संतरा',
      'bn': 'কমলা',
      'as': 'কমলা',
      'ne': 'सुन्तला',
    },
    'groc_coconut': {
      'en': 'Coconut',
      'hi': 'नारियल',
      'bn': 'নারকেল',
      'as': 'নাৰিকল',
      'ne': 'नरिवल',
    },
    'groc_cabbage': {
      'en': 'Cabbage',
      'hi': 'पत्तागोभी',
      'bn': 'বাঁধাকপি',
      'as': 'বন্ধাকবি',
      'ne': 'बन्दागोभी',
    },
    'groc_peas': {
      'en': 'Peas',
      'hi': 'मटर',
      'bn': 'মটরশুঁটি',
      'as': 'মটৰ',
      'ne': 'केराउ',
    },
    'groc_garlic': {
      'en': 'Garlic',
      'hi': 'लहसुन',
      'bn': 'রসুন',
      'as': 'নহৰু',
      'ne': 'लसुन',
    },
    'groc_sugarcane': {
      'en': 'Sugarcane',
      'hi': 'गन्ना',
      'bn': 'আখ',
      'as': 'কুঁহিয়াৰ',
      'ne': 'उखु',
    },
    'groc_milk': {
      'en': 'Milk',
      'hi': 'दूध',
      'bn': 'দুধ',
      'as': 'গাখীৰ',
      'ne': 'दूध',
    },
    'groc_bread': {
      'en': 'Bread',
      'hi': 'ब्रेड',
      'bn': 'পাউরুটি',
      'as': 'পাউৰুটী',
      'ne': 'पाउरोटी',
    },
    'groc_tea': {
      'en': 'Tea',
      'hi': 'चायपत्ती',
      'bn': 'চা পাতা',
      'as': 'চাহপাত',
      'ne': 'चियापत्ती',
    },
    'groc_coffee': {
      'en': 'Coffee',
      'hi': 'कॉफ़ी',
      'bn': 'কফি',
      'as': 'কফি',
      'ne': 'कफी',
    },
    'groc_biscuits': {
      'en': 'Biscuits',
      'hi': 'बिस्कुट',
      'bn': 'বিস্কুট',
      'as': 'বিস্কুট',
      'ne': 'बिस्कुट',
    },
    'groc_eggs': {
      'en': 'Eggs',
      'hi': 'अंडे',
      'bn': 'ডিম',
      'as': 'কণী',
      'ne': 'अन्डा',
    },
    'groc_potato': {
      'en': 'Potato',
      'hi': 'आलू',
      'bn': 'আলু',
      'as': 'আলু',
      'ne': 'आलु',
    },
    'groc_tomato': {
      'en': 'Tomato',
      'hi': 'टमाटर',
      'bn': 'টমেটো',
      'as': 'টমেটো',
      'ne': 'गोलभेंडा',
    },
    'groc_onion': {
      'en': 'Onion',
      'hi': 'प्याज़',
      'bn': 'পেঁয়াজ',
      'as': 'পিয়াঁজ',
      'ne': 'प्याज',
    },
    'groc_carrot': {
      'en': 'Carrot',
      'hi': 'गाजर',
      'bn': 'গাজর',
      'as': 'গাজৰ',
      'ne': 'गाजर',
    },
    'groc_brinjal': {
      'en': 'Brinjal',
      'hi': 'बैंगन',
      'bn': 'বেগুন',
      'as': 'বেঙেনা',
      'ne': 'भन्टा',
    },
    'groc_green_chilli': {
      'en': 'Green Chilli',
      'hi': 'हरी मिर्च',
      'bn': 'কাঁচা মরিচ',
      'as': 'কেঁচা জলকীয়া',
      'ne': 'हरियो खुर्सानी',
    },
    'groc_spinach': {
      'en': 'Spinach',
      'hi': 'पालक',
      'bn': 'পালং শাক',
      'as': 'পালেং শাক',
      'ne': 'पालुङ्गो',
    },
    'groc_corn': {
      'en': 'Corn',
      'hi': 'भुट्टा / मक्का',
      'bn': 'ভুট্টা',
      'as': 'মাকৈ',
      'ne': 'मकै',
    },
    'groc_honey': {
      'en': 'Honey',
      'hi': 'शहद',
      'bn': 'মধু',
      'as': 'মৌ',
      'ne': 'मह',
    },
  };

  /// Full 30 Object Items catalogue for Remember Objects Game
  static const List<GameItem> defaultEverydayItems = [
    GameItem(
      id: 'rose',
      name: 'Garden Rose',
      imagePath: 'assets/images/objects/rose.png',
      emoji: '🌹',
      fallbackIcon: Icons.local_florist_rounded,
      tintColor: Color(0xFFE91E63),
      category: 'garden',
    ),
    GameItem(
      id: 'glasses',
      name: 'Reading Glasses',
      imagePath: 'assets/images/objects/glasses.png',
      emoji: '👓',
      fallbackIcon: Icons.visibility_rounded,
      tintColor: Color(0xFF455A64),
      category: 'personal',
    ),
    GameItem(
      id: 'camera',
      name: 'Photo Camera',
      imagePath: 'assets/images/objects/camera.png',
      emoji: '📷',
      fallbackIcon: Icons.camera_alt_rounded,
      tintColor: Color(0xFF5E35B1),
      category: 'leisure',
    ),
    GameItem(
      id: 'umbrella',
      name: 'Umbrella',
      imagePath: 'assets/images/objects/umbrella.png',
      emoji: '☂️',
      fallbackIcon: Icons.umbrella_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'clothing',
    ),
    GameItem(
      id: 'key',
      name: 'Key',
      imagePath: 'assets/images/objects/key.png',
      emoji: '🔑',
      fallbackIcon: Icons.vpn_key_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'household',
    ),
    GameItem(
      id: 'tea_cup',
      name: 'Tea Cup',
      imagePath: 'assets/images/objects/tea_cup.png',
      emoji: '☕',
      fallbackIcon: Icons.local_cafe_rounded,
      tintColor: Color(0xFF795548),
      category: 'kitchen',
    ),
    GameItem(
      id: 'clock',
      name: 'Clock',
      imagePath: 'assets/images/objects/clock.png',
      emoji: '⏰',
      fallbackIcon: Icons.access_time_filled_rounded,
      tintColor: Color(0xFF00897B),
      category: 'household',
    ),
    GameItem(
      id: 'book',
      name: 'Book',
      imagePath: 'assets/images/objects/book.png',
      emoji: '📖',
      fallbackIcon: Icons.menu_book_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'leisure',
    ),
    GameItem(
      id: 'apple',
      name: 'Apple',
      imagePath: 'assets/images/objects/apple.png',
      emoji: '🍎',
      fallbackIcon: Icons.apple,
      tintColor: Color(0xFFD32F2F),
      category: 'fruit',
    ),
    GameItem(
      id: 'banana',
      name: 'Banana',
      imagePath: 'assets/images/objects/banana.png',
      emoji: '🍌',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'fruit',
    ),
    GameItem(
      id: 'water_bottle',
      name: 'Water Bottle',
      imagePath: 'assets/images/objects/water_bottle.png',
      emoji: '🧴',
      fallbackIcon: Icons.water_drop_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'kitchen',
    ),
    GameItem(
      id: 'handbag',
      name: 'Handbag',
      imagePath: 'assets/images/objects/handbag.png',
      emoji: '👜',
      fallbackIcon: Icons.shopping_bag_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'personal',
    ),
    GameItem(
      id: 'cap',
      name: 'Cap',
      imagePath: 'assets/images/objects/cap.png',
      emoji: '🧢',
      fallbackIcon: Icons.sports_baseball_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'clothing',
    ),
    GameItem(
      id: 'pencil',
      name: 'Pencil',
      imagePath: 'assets/images/objects/pencil.png',
      emoji: '✏️',
      fallbackIcon: Icons.edit_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'leisure',
    ),
    GameItem(
      id: 'radio',
      name: 'Radio',
      imagePath: 'assets/images/objects/radio.png',
      emoji: '📻',
      fallbackIcon: Icons.radio_rounded,
      tintColor: Color(0xFF5D4037),
      category: 'leisure',
    ),
    GameItem(
      id: 'toothbrush',
      name: 'Toothbrush',
      imagePath: 'assets/images/objects/toothbrush.png',
      emoji: '🪥',
      fallbackIcon: Icons.cleaning_services_rounded,
      tintColor: Color(0xFF03A9F4),
      category: 'personal',
    ),
    GameItem(
      id: 'candle',
      name: 'Candle',
      imagePath: 'assets/images/objects/candle.png',
      emoji: '🕯️',
      fallbackIcon: Icons.light_mode_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'household',
    ),
    GameItem(
      id: 'plant',
      name: 'Plant',
      imagePath: 'assets/images/objects/plant.png',
      emoji: '🪴',
      fallbackIcon: Icons.yard_rounded,
      tintColor: Color(0xFF388E3C),
      category: 'garden',
    ),
    GameItem(
      id: 'spoon',
      name: 'Spoon',
      imagePath: 'assets/images/objects/spoon.png',
      emoji: '🥄',
      fallbackIcon: Icons.restaurant_rounded,
      tintColor: Color(0xFF78909C),
      category: 'kitchen',
    ),
    GameItem(
      id: 'rice_bowl',
      name: 'Rice Bowl',
      imagePath: 'assets/images/objects/rice_bowl.png',
      emoji: '🍚',
      fallbackIcon: Icons.ramen_dining_rounded,
      tintColor: Color(0xFF37474F),
      category: 'kitchen',
    ),
    GameItem(
      id: 'basket',
      name: 'Basket',
      imagePath: 'assets/images/objects/basket.png',
      emoji: '🧺',
      fallbackIcon: Icons.shopping_basket_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'household',
    ),
    GameItem(
      id: 'shoe',
      name: 'Shoe',
      imagePath: 'assets/images/objects/shoe.png',
      emoji: '👞',
      fallbackIcon: Icons.roller_skating_rounded,
      tintColor: Color(0xFF4E342E),
      category: 'clothing',
    ),
    GameItem(
      id: 'scarf',
      name: 'Scarf',
      imagePath: 'assets/images/objects/scarf.png',
      emoji: '🧣',
      fallbackIcon: Icons.dry_cleaning_rounded,
      tintColor: Color(0xFFC62828),
      category: 'clothing',
    ),
    GameItem(
      id: 'wallet',
      name: 'Wallet',
      imagePath: 'assets/images/objects/wallet.png',
      emoji: '👛',
      fallbackIcon: Icons.account_balance_wallet_rounded,
      tintColor: Color(0xFF5D4037),
      category: 'personal',
    ),
    GameItem(
      id: 'comb',
      name: 'Comb',
      imagePath: 'assets/images/objects/comb.png',
      emoji: '🪮',
      fallbackIcon: Icons.content_cut_rounded,
      tintColor: Color(0xFF795548),
      category: 'personal',
    ),
    GameItem(
      id: 'mug',
      name: 'Mug',
      imagePath: 'assets/images/objects/mug.png',
      emoji: '☕',
      fallbackIcon: Icons.coffee_rounded,
      tintColor: Color(0xFF00897B),
      category: 'kitchen',
    ),
    GameItem(
      id: 'lamp',
      name: 'Lamp',
      imagePath: 'assets/images/objects/lamp.png',
      emoji: '🛋️',
      fallbackIcon: Icons.lightbulb_outline_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'household',
    ),
    GameItem(
      id: 'bell',
      name: 'Bell',
      imagePath: 'assets/images/objects/bell.png',
      emoji: '🔔',
      fallbackIcon: Icons.notifications_active_rounded,
      tintColor: Color(0xFFFFB300),
      category: 'household',
    ),
    GameItem(
      id: 'watch',
      name: 'Watch',
      imagePath: 'assets/images/objects/watch.png',
      emoji: '⌚',
      fallbackIcon: Icons.watch_rounded,
      tintColor: Color(0xFF3E2723),
      category: 'personal',
    ),
    GameItem(
      id: 'sweater',
      name: 'Sweater',
      imagePath: 'assets/images/objects/sweater.png',
      emoji: '🧥',
      fallbackIcon: Icons.checkroom_rounded,
      tintColor: Color(0xFF546E7A),
      category: 'clothing',
    ),
  ];

  /// Full 30 Grocery Items catalogue for Grocery Memory Game
  static const List<GameItem> defaultGroceryItems = [
    GameItem(
      id: 'groc_rice',
      name: 'Rice',
      imagePath: 'assets/images/groceries/rice.png',
      emoji: '🍚',
      fallbackIcon: Icons.rice_bowl_rounded,
      tintColor: Color(0xFF37474F),
      category: 'grains',
    ),
    GameItem(
      id: 'groc_dal',
      name: 'Dal',
      imagePath: 'assets/images/groceries/dal.png',
      emoji: '🍲',
      fallbackIcon: Icons.soup_kitchen_rounded,
      tintColor: Color(0xFFF57F17),
      category: 'pulses',
    ),
    GameItem(
      id: 'groc_wheat',
      name: 'Wheat',
      imagePath: 'assets/images/groceries/wheat.png',
      emoji: '🌾',
      fallbackIcon: Icons.grass_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'grains',
    ),
    GameItem(
      id: 'groc_salt',
      name: 'Salt',
      imagePath: 'assets/images/groceries/salt.png',
      emoji: '🧂',
      fallbackIcon: Icons.grain_rounded,
      tintColor: Color(0xFF78909C),
      category: 'spices',
    ),
    GameItem(
      id: 'groc_sugar',
      name: 'Sugar',
      imagePath: 'assets/images/groceries/sugar.png',
      emoji: '🍬',
      fallbackIcon: Icons.kitchen_rounded,
      tintColor: Color(0xFF0288D1),
      category: 'pantry',
    ),
    GameItem(
      id: 'groc_oil',
      name: 'Cooking Oil',
      imagePath: 'assets/images/groceries/cooking_oil.png',
      emoji: '🛢️',
      fallbackIcon: Icons.opacity_rounded,
      tintColor: Color(0xFFFFB300),
      category: 'pantry',
    ),
    GameItem(
      id: 'groc_banana',
      name: 'Banana',
      imagePath: 'assets/images/groceries/banana.png',
      emoji: '🍌',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFBC02D),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_apple',
      name: 'Apple',
      imagePath: 'assets/images/groceries/apple.png',
      emoji: '🍎',
      fallbackIcon: Icons.apple,
      tintColor: Color(0xFFD32F2F),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_mango',
      name: 'Mango',
      imagePath: 'assets/images/groceries/mango.png',
      emoji: '🥭',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_orange',
      name: 'Orange',
      imagePath: 'assets/images/groceries/orange.png',
      emoji: '🍊',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFFFB8C00),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_coconut',
      name: 'Coconut',
      imagePath: 'assets/images/groceries/coconut.png',
      emoji: '🥥',
      fallbackIcon: Icons.circle_outlined,
      tintColor: Color(0xFF5D4037),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_cabbage',
      name: 'Cabbage',
      imagePath: 'assets/images/groceries/cabbage.png',
      emoji: '🥬',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF43A047),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_peas',
      name: 'Peas',
      imagePath: 'assets/images/groceries/peas.png',
      emoji: '🟢',
      fallbackIcon: Icons.lens_rounded,
      tintColor: Color(0xFF7CB342),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_garlic',
      name: 'Garlic',
      imagePath: 'assets/images/groceries/garlic.png',
      emoji: '🧄',
      fallbackIcon: Icons.spa_rounded,
      tintColor: Color(0xFF90A4AE),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_sugarcane',
      name: 'Sugarcane',
      imagePath: 'assets/images/groceries/sugarcane.png',
      emoji: '🎋',
      fallbackIcon: Icons.park_rounded,
      tintColor: Color(0xFF689F38),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_milk',
      name: 'Milk',
      imagePath: 'assets/images/groceries/milk.png',
      emoji: '🥛',
      fallbackIcon: Icons.local_drink_rounded,
      tintColor: Color(0xFF1976D2),
      category: 'dairy',
    ),
    GameItem(
      id: 'groc_bread',
      name: 'Bread',
      imagePath: 'assets/images/groceries/bread.png',
      emoji: '🍞',
      fallbackIcon: Icons.bakery_dining_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'bakery',
    ),
    GameItem(
      id: 'groc_tea',
      name: 'Tea',
      imagePath: 'assets/images/groceries/tea.png',
      emoji: '🍵',
      fallbackIcon: Icons.emoji_food_beverage_rounded,
      tintColor: Color(0xFF388E3C),
      category: 'beverages',
    ),
    GameItem(
      id: 'groc_coffee',
      name: 'Coffee',
      imagePath: 'assets/images/groceries/coffee.png',
      emoji: '☕',
      fallbackIcon: Icons.local_cafe_rounded,
      tintColor: Color(0xFF4E342E),
      category: 'beverages',
    ),
    GameItem(
      id: 'groc_biscuits',
      name: 'Biscuits',
      imagePath: 'assets/images/groceries/biscuits.png',
      emoji: '🍪',
      fallbackIcon: Icons.cookie_rounded,
      tintColor: Color(0xFFFB8C00),
      category: 'snacks',
    ),
    GameItem(
      id: 'groc_eggs',
      name: 'Eggs',
      imagePath: 'assets/images/groceries/eggs.png',
      emoji: '🥚',
      fallbackIcon: Icons.egg_rounded,
      tintColor: Color(0xFFFFB74D),
      category: 'dairy',
    ),
    GameItem(
      id: 'groc_potato',
      name: 'Potato',
      imagePath: 'assets/images/groceries/potato.png',
      emoji: '🥔',
      fallbackIcon: Icons.crop_square_rounded,
      tintColor: Color(0xFF8D6E63),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_tomato',
      name: 'Tomato',
      imagePath: 'assets/images/groceries/tomato.png',
      emoji: '🍅',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFFE53935),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_onion',
      name: 'Onion',
      imagePath: 'assets/images/groceries/onion.png',
      emoji: '🧅',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFF8E24AA),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_carrot',
      name: 'Carrot',
      imagePath: 'assets/images/groceries/carrot.png',
      emoji: '🥕',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFF57C00),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_brinjal',
      name: 'Brinjal',
      imagePath: 'assets/images/groceries/brinjal.png',
      emoji: '🍆',
      fallbackIcon: Icons.circle,
      tintColor: Color(0xFF4A148C),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_green_chilli',
      name: 'Green Chilli',
      imagePath: 'assets/images/groceries/green_chilli.png',
      emoji: '🌶️',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF2E7D32),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_spinach',
      name: 'Spinach',
      imagePath: 'assets/images/groceries/spinach.png',
      emoji: '🥬',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFF1B5E20),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_corn',
      name: 'Corn',
      imagePath: 'assets/images/groceries/corn.png',
      emoji: '🌽',
      fallbackIcon: Icons.eco_rounded,
      tintColor: Color(0xFFFDD835),
      category: 'produce',
    ),
    GameItem(
      id: 'groc_honey',
      name: 'Honey',
      imagePath: 'assets/images/groceries/honey.png',
      emoji: '🍯',
      fallbackIcon: Icons.breakfast_dining_rounded,
      tintColor: Color(0xFFFFA000),
      category: 'pantry',
    ),
  ];
}
